AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Api & Side For describing EC2 instance info

Parameters:
  Domain:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-.]{1,63}'
  Repo:
    Type: String
  DeployCertificates:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
  GoogleClientId:
    Type: String
    Default: ''
  GoogleSecret:
    Type: String
    Default: ''
    NoEcho: true
  FacebookClientId:
    Type: String
    Default: ''
  FacebookSecret:
    Type: String
    Default: ''
    NoEcho: true


Conditions:
  DeployCertificates: !Equals [!Ref DeployCertificates, 'true']
  Google: !Not [!Equals [!Ref GoogleClientId, '']]
  Facebook: !Not [!Equals [!Ref FacebookClientId, '']]

Resources:
  Api:
    Condition: DeployCertificates
    Type: AWS::Serverless::HttpApi
    Properties:
      FailOnWarnings: true
      AccessLogSettings:
        DestinationArn: !GetAtt ApiAccessLogs.Arn
        Format: $context.requestId,$context.requestTime,$context.resourcePath,$context.identity.caller,$context.identity.sourceIp
      Domain:
        CertificateArn: !Ref ApiCertificate
        DomainName: !Sub 'api.${Domain}'
        Route53:
          HostedZoneId: !Ref HostedZone
          IpV6: true
      CorsConfiguration:
        AllowCredentials: true
        AllowHeaders:
          - Authorization
        AllowMethods:
          - GET
        AllowOrigins:
          - !Sub https://${Domain}
      Auth:
        DefaultAuthorizer: JwtAuthorizer
        Authorizers:
          JwtAuthorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}
              audience:
               - !Ref UserPoolClient

  ApiAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 90

  ApiCertificate:
    Condition: DeployCertificates
    DependsOn: CAARecords
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub api.${Domain}
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub api.${Domain}
          HostedZoneId: !Ref HostedZone

  RootCertificate:
    Condition: DeployCertificates
    DependsOn: CAARecords
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Domain
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref Domain
          HostedZoneId: !Ref HostedZone

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref Domain

  CAARecords:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref Domain
      Type: CAA
      TTL: 3600
      ResourceRecords:
        - 0 issue "amazon.com"
        - 0 issue "amazontrust.com"
        - 0 issue "awstrust.com"
        - 0 issue "amazonaws.com"
        - 0 issue ";"

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      Policies:
        PasswordPolicy:
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          MinimumLength: 8
      UserPoolAddOns:
        AdvancedSecurityMode: AUDIT
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      UserPoolId: !Ref UserPool
      PreventUserExistenceErrors: ENABLED
      GenerateSecret: true
      CallbackURLs:
        - !Sub https://${Domain}
      LogoutURLs:
        - !Sub https://${Domain}
      SupportedIdentityProviders:
        - COGNITO
        - !If [Google,  !Select [0, !Split [Login, !Ref GoogleLoginProvider]], !Ref AWS::NoValue]
        - !If [Facebook,  !Select [0, !Split [Login, !Ref FacebookLoginProvider]], !Ref AWS::NoValue]

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Select [0, !Split [., !Ref Domain]]
      UserPoolId: !Ref UserPool

  GoogleLoginProvider:
    Condition: Google
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Google
      ProviderType: Google
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleSecret
        authorize_scopes: profile email openid
      AttributeMapping:
        email: email

  FacebookLoginProvider:
    Condition: Facebook
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: Facebook
      ProviderType: Facebook
      ProviderDetails:
        client_id: !Ref FacebookClientId
        client_secret: !Ref FacebookSecret
        authorize_scopes: public_profile,email
      AttributeMapping:
        email: email

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Domain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: GetOriginAccessIdentity
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}
            Action: s3:GetObject
            Resource: !Sub '${Bucket.Arn}/*'

  Route53RecordIPv4:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref HostedZone
      Name: !Ref Domain
      Type: A

  Route53RecordIPv6:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref HostedZone
      Name: !Ref Domain
      Type: AAAA

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: !If [DeployCertificates, [!Ref Domain], !Ref AWS::NoValue]
        Enabled: true
        IPV6Enabled: true
        PriceClass: PriceClass_100
        ViewerCertificate: !If
          - DeployCertificates
          - AcmCertificateArn: !Ref RootCertificate
            SslSupportMethod: sni-only
          - !Ref AWS::NoValue
        Origins:
          - Id: s3origin
            DomainName: !GetAtt Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          DefaultTTL: 900
          TargetOriginId: s3origin
          ViewerProtocolPolicy: allow-all
          Compress: True
          ForwardedValues:
            QueryString: False

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub OriginAccessIdentity for ${Domain}

  DescribeInstancesFunction:
    Condition: DeployCertificates
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: main.main
      InlineCode: |
        def main(event, context):
          msg = "Build template with make all, package or package-cfn"
          print(msg)
          print(f"invoked with ${event} ${context}")
          return {
            "statusCode": 500,
            "body": msg
          }
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: GET
            Path: /
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            - Effect: Allow
              Action: ec2:DescribeInstances
              Resource: '*'

  GithubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - a031c46782e6e6c662c2c87c76da9aa62ccabd8e
      Url: https://token.actions.githubusercontent.com

  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Federated: !Ref GithubOIDCProvider
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              token.actions.githubusercontent.com:sub: !Sub repo:${Repo}:environment:${Domain}

  DeploymentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - !Ref DeploymentRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: cloudformation:DescribeStacks
            Resource: '*'
          - Effect: Allow
            Action:
              - cloudformation:DescribeChangeSet
              - cloudformation:GetTemplateSummary
            Resource: !Ref AWS::StackId
          - Effect: Allow
            Action:
              - cloudformation:DeleteChangeSet
              - cloudformation:ExecuteChangeSet
            Resource: !Ref AWS::StackId
            Condition:
              StringNotLike:
                cloudformation:ChangeSetName: diff-change-set-*
          - Effect: Allow
            Action: cloudformation:CreateChangeSet
            Resource: !Ref AWS::StackId
            Condition:
              ArnEquals:
                cloudformation:RoleArn: !GetAtt MainStackRole.Arn
              StringNotLike:
                cloudformation:ChangeSetName: diff-change-set-*
          - Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:UpdateStack
              - cloudformation:DeleteStack
            Resource: !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}-integration-test-stack/*
          - Effect: Allow
            Action: iam:PassRole
            Resource:
              - !GetAtt IntegrationTestStackRole.Arn
              - !GetAtt MainStackRole.Arn
          - Effect: Allow
            Action:
              - cognito-idp:AdminConfirmSignUp
              - cognito-idp:AdminDeleteUser
            Resource: !GetAtt UserPool.Arn
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: !Sub ${Bucket.Arn}/*
          - Effect: Allow
            Action: s3:ListBucket
            Resource: !GetAtt Bucket.Arn
          - Effect: Allow
            Action:
              - ec2:StartInstances
              - ec2:StopInstances
            Resource: '*'
            Condition:
              StringEquals:
                ec2:ResourceTag/aws:cloudformation:stack-name: !Sub ${AWS::StackName}-integration-test-stack
          - Effect: Allow
            Action: ec2:DescribeInstances
            Resource: '*'
          - !If
            - DeployCertificates
            - Effect: Allow
              Action: cloudfront:CreateInvalidation
              Resource: !Sub arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudfrontDistribution}
            - !Ref AWS::NoValue

  MainStackRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: cloudformation.amazonaws.com
      Policies:
        - PolicyName: extraPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: cloudformation:ExecuteChangeSet
                Resource: !Ref AWS::StackId

  MainStackPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
       - !Ref DiffStackRole
       - !Ref MainStackRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: cloudformation:CreateChangeSet
            Resource:
              - !Ref AWS::StackId
              - !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31
          - Effect: Allow
            Action:
              - apigateway:*
              - acm:*
              - cloudfront:*
              - logs:*
              - route53:GetHostedZone
              - route53:CreateHostedZone
              - route53:UpdateHostedZoneComment
              - route53:ListTagsForResource
              - route53:ListQueryLoggingConfigs
              - route53:GetChange
              - s3:CreateBucket
              - cognito-idp:CreateUserPool
              - cognito-idp:UpdateUserPool
              - cognito-idp:CreateIdentityProvider
              - cognito-idp:UpdateIdentityProvider
              - cognito-idp:DeleteIdentityProvider
              - lambda:CreateFunction
              - iam:GetRole
              - iam:GetUser
              - iam:GetPolicy
              - iam:ListPolicyVersions
              - iam:GetPolicyVersion
              - iam:GetRolePolicy
              - iam:GetUserPolicy
              - iam:ListPolicyTags
              - iam:ListRoleTags
              - iam:ListUserTags
              - iam:GetOpenIDConnectProvider
            Resource: '*'
          - Effect: Allow
            Action: route53:ChangeResourceRecordSets
            Resource: !Sub arn:${AWS::Partition}:route53:::hostedzone/${HostedZone}
          - Effect: Allow
            Action:
              - s3:PutBucketPolicy
              - s3:DeleteBucketPolicy
              - s3:DeleteBucket
            Resource: !GetAtt Bucket.Arn
          - Effect: Allow
            Action:
              - cognito-idp:CreateUserPoolClient
              - cognito-idp:UpdateUserPoolClient
              - cognito-idp:DeleteUserPoolClient
              - cognito-idp:CreateUserPoolDomain
              - cognito-idp:UpdateUserPoolDomain
              - cognito-idp:DeleteUserPoolDomain
              - cognito-idp:SetRiskConfiguration
              - cognito-idp:SetUICustomization
              - cognito-idp:SetUserPoolMfaConfig
            Resource: !GetAtt UserPool.Arn
          - !If
            - DeployCertificates
            - Effect: Allow
              Action:
                - lambda:AddPermission
                - lambda:RemovePermission
                - lambda:UpdateFunctionCode
                - lambda:DeleteFunction
                - lambda:UpdateFunctionConfiguration
                - lambda:CreateEventSourceMapping
                - lambda:UpdateEventSourceMapping
                - lambda:DeleteEventSourceMapping
                - lambda:PutFunctionEventInvokeConfig
                - lambda:UpdateFunctionEventInvokeConfig
                - lambda:DeleteFunctionEventInvokeConfig
                - lambda:TagResource
                - lambda:UntagResource
              Resource: !GetAtt DescribeInstancesFunction.Arn
            - !Ref AWS::NoValue

  CreateDiffRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Federated: !Ref GithubOIDCProvider
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringLike:
              token.actions.githubusercontent.com:sub: !Sub repo:${Repo}:*
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:GetTemplateSummary
                Resource: !Ref AWS::StackId
              - Effect: Allow
                Action: cloudformation:CreateChangeSet
                Resource: !Ref AWS::StackId
                Condition:
                  ArnEquals:
                    cloudformation:RoleArn: !GetAtt DiffStackRole.Arn
                  StringLike:
                    cloudformation:ChangeSetName: diff-change-set-*
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt DiffStackRole.Arn

  DiffStackRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: cloudformation.amazonaws.com
      Policies:
        - PolicyName: extraPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:UpdateRole
                  - iam:DeleteRole
                  - iam:AttachRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:UpdateAssumeRolePolicy
                  - iam:UpdateRoleDescription
                  - iam:CreatePolicyVersion
                  - iam:DeletePolicyVersion
                  - iam:SetDefaultPolicyVersion
                  - iam:PassRole
                  - iam:DeletePolicy
                  - iam:ListAccessKeys
                  - iam:CreateOpenIDConnectProvider
                  - iam:DeleteOpenIDConnectProvider
                  - iam:UpdateOpenIDConnectProviderThumbprint
                  - iam:AddClientIDToOpenIDConnectProvider
                  - iam:RemoveClientIDFromOpenIDConnectProvider
                  - idp:DeleteUserPool
                  - route53:DeleteHostedZone
                  - lambda:AddPermission
                  - lambda:RemovePermission
                  - lambda:DeleteFunction
                Resource: '*'

  IntegrationTestStackRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: cloudformation.amazonaws.com
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:RunInstances
                  - ec2:TerminateInstances
                  - ec2:DescribeInstances
                Resource: '*'
              - Effect: Allow
                Action: ssm:GetParameters
                Resource: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}::parameter/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2

Outputs:
  ApiId:
    Condition: DeployCertificates
    Value: !Ref Api
  SiteDistributionId:
    Value: !Ref CloudfrontDistribution
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  NameServers:
    Value: !Join ["," , !GetAtt HostedZone.NameServers]
  MainStackRole:
    Value: !GetAtt MainStackRole.Arn
  DiffStackRole:
    Value: !GetAtt DiffStackRole.Arn
  IntegrationTestStackRole:
    Value: !GetAtt IntegrationTestStackRole.Arn
  DeploymentRole:
    Value: !GetAtt DeploymentRole.Arn
  CreateDiffRole:
    Value: !GetAtt CreateDiffRole.Arn
