name: Create Diff for ec2dash.juancanham.com
on:
  pull_request:
    branches:
      - main
jobs:
  Diff:
    env:
      DOMAIN: ec2dash.juancanham.com
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: ec2dash.juancanham.com
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: make diff DOMAIN=$DOMAIN
