Name: Create Diff for ec2dash.juancanham.com
on:
  pull_request:
    branches:
      - main
jobs:
  Diff:
    env:
      DOMAIN: ec2dash.juancanham.com
    runs-on: ubuntu-latest
    steps:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: make diff DOMAIN=$DOMAIN
