name: Create Change Set for ec2dash.juancanham.com
'on':
  pull_request:
    branches:
      - main
jobs:
  Diff:
    permissions:
      id-token: write
      contents: read
    env:
      DOMAIN: ec2dash.juancanham.com
      AWS_DEFAULT_REGION: us-east-1
    runs-on: ubuntu-latest
    environment: ec2dash.juancanham.com-diff
    steps:
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::761680974830:role/ec2dash-juancanham-com-CreateDiffRole-12DXV7SUVFCEJ
          aws-region: us-east-1
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: make diff DOMAIN=$DOMAIN
