name: deploy ec2dash.juancanham.com
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    permissions:
      id-token: write
      contents: read
    env:
      MOZ_HEADLESS: 1
      DOMAIN: ec2dash.juancanham.com
    runs-on: ubuntu-latest
    environment: ec2dash.juancanham.com
    concurrency: ec2dash.juancanham.com
    steps:
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::761680974830:role/ec2dash-juancanham-com-DeploymentRole-GC1IXP2ZAXRS
          aws-region: us-east-1
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: make all DOMAIN=$DOMAIN
      - name: Revert last commit due to failure
        if: ${{ failure() }}
        run: "if $(git log -1 | grep revert); then\n  git revert HEAD\n  git push\n\
          fi\n"
