name: Validation
on:
  push:
    branches-ignore:
      - main
jobs:
  Build-Lint-Test:
    env:
      AWS_DEFAULT_REGION: us-east-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: make pre